/* Generated by rze. Waybar CSS include. */

:root {
  --rze-bg: {{ bg }};
  --rze-fg: {{ fg }};
  --rze-c0: {{ c0 }};
  --rze-c1: {{ c1 }};
  --rze-c2: {{ c2 }};
  --rze-c3: {{ c3 }};
  --rze-c4: {{ c4 }};
  --rze-c5: {{ c5 }};
  --rze-c6: {{ c6 }};
  --rze-c7: {{ c7 }};
  --rze-c8: {{ c8 }};
  --rze-c9: {{ c9 }};
  --rze-c10: {{ c10 }};
  --rze-c11: {{ c11 }};
  --rze-c12: {{ c12 }};
  --rze-c13: {{ c13 }};
  --rze-c14: {{ c14 }};
  --rze-c15: {{ c15 }};
}
