# Generated by rze. Dunst include fragment.

[global]
frame_color = "{{ c4 }}"

[urgency_low]
background = "{{ bg }}"
foreground = "{{ fg }}"

[urgency_normal]
background = "{{ bg }}"
foreground = "{{ fg }}"

[urgency_critical]
background = "{{ c1 }}"
foreground = "{{ bg }}"
frame_color = "{{ c1 }}"
