# Generated by rze. Cava theme.

[color]
background = '{{ bg }}'
foreground = '{{ fg }}'
gradient = 1
gradient_color_1 = '{{ c1 }}'
gradient_color_2 = '{{ c2 }}'
gradient_color_3 = '{{ c3 }}'
gradient_color_4 = '{{ c4 }}'
gradient_color_5 = '{{ c5 }}'
gradient_color_6 = '{{ c6 }}'
gradient_color_7 = '{{ c7 }}'
gradient_color_8 = '{{ c8 }}'
